import {
  FaChartBar,
  FaClipboardList,
  FaCode,
  FaNetworkWired,
  FaUsers,
} from "react-icons/fa";

export const CATEGORIES_CARDS_DATA = [
  {
    name: "Product Management",
    logo: "fas fa-briefcase text-blue-500 text-3xl mb-2",
  },
  {
    name: "Engineering Management",
    logo: "fas fa-users text-blue-500 text-3xl mb-2",
  },
  {
    name: "Software Engineering",
    logo: "fas fa-code text-blue-500 text-3xl mb-2",
  },
  {
    name: "System Design",
    logo: "fas fa-puzzle-piece text-blue-500 text-3xl mb-2",
  },
  {
    name: "Data Science",
    logo: "fas fa-chart-line text-blue-500 text-3xl mb-2",
  },
  {
    name: "Machine Learning",
    logo: "fas fa-robot text-blue-500 text-3xl mb-2",
  },
  {
    name: "TPM",
    logo: "fas fa-cogs text-blue-500 text-3xl mb-2",
  },
  {
    name: "Machine Learning",
    logo: "fas fa-robot text-blue-500 text-3xl mb-2",
  },
  {
    name: "TPM",
    logo: "fas fa-cogs text-blue-500 text-3xl mb-2",
  },
  {
    name: "Machine Learning",
    logo: "fas fa-robot text-blue-500 text-3xl mb-2",
  },
  {
    name: "TPM",
    logo: "fas fa-cogs text-blue-500 text-3xl mb-2",
  },
  {
    name: "Machine Learning",
    logo: "fas fa-robot text-blue-500 text-3xl mb-2",
  },
  {
    name: "TPM",
    logo: "fas fa-cogs text-blue-500 text-3xl mb-2",
  },
];
export const MNC_DATA = [
  {
    name: "Meta",
    logo: "fab fa-meta fa-3x text-blue-600",
  },
  {
    name: "Meta",
    logo: "fab fa-google fa-3x text-blue-600",
  },
  {
    name: "Google",
    logo: "fab fa-meta fa-3x text-blue-600",
  },
  {
    name: "Microsoft",
    logo: "fab fa-microsoft fa-3x text-green-600",
  },
  {
    name: "Meta",
    logo: "fab fa-amazon fa-3x text-yellow-500",
  },
  {
    name: "Amazon",
    logo: "fab fa-meta fa-3x text-blue-600",
  },
  {
    name: "Meta",
    logo: "fab fa-openai fa-3x text-gray-500",
  },
  {
    name: "OpenAI",
    logo: "fab fa-meta fa-3x text-blue-600",
  },
  {
    name: "Airbnb",
    logo: "fab fa-airbnb fa-3x text-red-500",
  },
  {
    name: "Meta",
    logo: "fab fa-facebook-f fa-3x text-blue-700",
  },
  {
    name: "Facebook",
    logo: "fab fa-meta fa-3x text-blue-600",
  },
  {
    name: "TikTok",
    logo: "fab fa-tiktok fa-3x text-black",
  },
  {
    name: "Stripe",
    logo: "fab fa-stripe fa-3x text-indigo-600",
  },
  {
    name: "IBM",
    logo: "fab fa-ibm fa-3x text-blue-600",
  },
  {
    name: "Salesforce",
    logo: "fab fa-salesforce fa-3x text-blue-500",
  },
  {
    name: "Uber",
    logo: "fab fa-uber fa-3x text-black",
  },
  {
    name: "Adobe",
    logo: "fab fa-adobe fa-3x text-red-600",
  },
  {
    name: "Pinterest",
    logo: "fab fa-pinterest fa-3x text-red-600",
  },
  {
    name: "Etsy",
    logo: "fab fa-etsy fa-3x text-green-600",
  },
  {
    name: "Yelp",
    logo: "fab fa-yelp fa-3x text-red-600",
  },
];

export const TAGS = [
  "All",
  "PM",
  "Machine Learning",
  "Data Science",
  "Security",
  "Web Development",
  "Mobile Development",
  "Cloud Computing",
  "DevOps",
  "Blockchain",
  "Artificial Intelligence",
  "Big Data",
  "Cybersecurity",
  "UI/UX Design",
  "Game Development",
  "Embedded Systems",
  "Networking",
  "IoT (Internet of Things)",
  "Data Engineering",
  "Quantum Computing",
  "Software Testing",
  "AR/VR (Augmented/Virtual Reality)",
  "Database Management",
  "Automation",
  "Digital Marketing",
];
export const ITEM_WIDTH = 240;

export const courseItems = [
  {
    name: "Product Management",
    description:
      "Ace product interviews from strategy cases to technical skills.",
    icon: <FaClipboardList />,
    id: 1,
  },
  {
    name: "Software Engineering",
    description: "Learn essential strategies for coding problems and more.",
    icon: <FaCode />,
    id: 2,
  },
  {
    name: "Data Science",
    description:
      "Execute statistical techniques and experimentation effectively.",
    icon: <FaChartBar />,
    id: 3,
  },
  {
    name: "Engineering Management",
    description: "Review key leadership and people management skills.",
    icon: <FaUsers />,
    id: 4,
  },
  {
    name: "System Design",
    description:
      "Define architectures, interfaces, and databases in a time crunch.",
    icon: <FaNetworkWired />,
    id: 5,
  },
];

export const COURSES = [
  {
    id: 101,
    title: "Intro to Product Management",
    description: "Learn the fundamentals of managing a product lifecycle.",
    courses: 5,
    students: "8k",
    image: "https://example.com/image101.jpg",
    categoryId: 1,
  },
  {
    id: 102,
    title: "Advanced Product Strategy",
    description: "Master advanced strategies in product management.",
    courses: 8,
    students: "12k",
    image: "https://example.com/image102.jpg",
    categoryId: 1,
  },
  {
    id: 103,
    title: "Roadmapping and Prioritization",
    description: "Learn how to roadmap and prioritize product features.",
    courses: 6,
    students: "6k",
    image: "https://example.com/image103.jpg",
    categoryId: 1,
  },
  {
    id: 104,
    title: "Metrics and KPIs in Product",
    description: "Understand key metrics and KPIs in product management.",
    courses: 4,
    students: "10k",
    image: "https://example.com/image104.jpg",
    categoryId: 1,
  },
  {
    id: 201,
    title: "Data Structures and Algorithms",
    description: "Learn the most commonly used data structures and algorithms.",
    courses: 10,
    students: "25k",
    image: "https://example.com/image201.jpg",
    categoryId: 2,
  },
  {
    id: 202,
    title: "System Design Basics",
    description: "Fundamentals of designing scalable and reliable systems.",
    courses: 7,
    students: "15k",
    image: "https://example.com/image202.jpg",
    categoryId: 2,
  },
  {
    id: 203,
    title: "Advanced Coding Interviews",
    description: "Prepare for advanced coding interviews with real problems.",
    courses: 12,
    students: "30k",
    image: "https://example.com/image203.jpg",
    categoryId: 2,
  },
  {
    id: 204,
    title: "Database Management",
    description: "Manage databases efficiently with best practices.",
    courses: 6,
    students: "18k",
    image: "https://example.com/image204.jpg",
    categoryId: 2,
  },
  {
    id: 301,
    title: "Statistics for Data Science",
    description: "Learn essential statistics concepts for data science.",
    courses: 8,
    students: "20k",
    image: "https://example.com/image301.jpg",
    categoryId: 3,
  },
  {
    id: 302,
    title: "Machine Learning Basics",
    description: "Introduction to machine learning techniques and tools.",
    courses: 10,
    students: "22k",
    image: "https://example.com/image302.jpg",
    categoryId: 3,
  },
  {
    id: 303,
    title: "Data Wrangling Techniques",
    description: "Master techniques for cleaning and organizing data.",
    courses: 5,
    students: "12k",
    image: "https://example.com/image303.jpg",
    categoryId: 3,
  },
  {
    id: 304,
    title: "Python for Data Science",
    description: "Learn how to use Python effectively in data science.",
    courses: 9,
    students: "30k",
    image: "https://example.com/image304.jpg",
    categoryId: 3,
  },
  {
    id: 401,
    title: "Leadership in Engineering",
    description: "Develop leadership skills in an engineering context.",
    courses: 6,
    students: "18k",
    image: "https://example.com/image401.jpg",
    categoryId: 4,
  },
  {
    id: 402,
    title: "Effective Communication",
    description: "Improve communication in engineering teams.",
    courses: 5,
    students: "14k",
    image: "https://example.com/image402.jpg",
    categoryId: 4,
  },
  {
    id: 403,
    title: "Building Teams",
    description: "Learn how to build and manage successful teams.",
    courses: 4,
    students: "10k",
    image: "https://example.com/image403.jpg",
    categoryId: 4,
  },
  {
    id: 404,
    title: "Conflict Resolution",
    description: "Master conflict resolution techniques in a team setting.",
    courses: 3,
    students: "9k",
    image: "https://example.com/image404.jpg",
    categoryId: 4,
  },
  {
    id: 501,
    title: "Introduction to System Design",
    description: "Learn the basics of system design from scratch.",
    courses: 6,
    students: "20k",
    image: "https://example.com/image501.jpg",
    categoryId: 5,
  },
  {
    id: 502,
    title: "Designing Scalable Systems",
    description: "Understand how to design scalable and maintainable systems.",
    courses: 8,
    students: "22k",
    image: "https://example.com/image502.jpg",
    categoryId: 5,
  },
  {
    id: 503,
    title: "Microservices Architecture",
    description: "Learn about microservices architecture and design patterns.",
    courses: 5,
    students: "15k",
    image: "https://example.com/image503.jpg",
    categoryId: 5,
  },
  {
    id: 504,
    title: "Design Patterns for Large Systems",
    description: "Discover design patterns for building large-scale systems.",
    courses: 7,
    students: "17k",
    image: "https://example.com/image504.jpg",
    categoryId: 5,
  },
  {
    id: 601,
    title: "Deep Learning Fundamentals",
    description: "Explore the fundamentals of deep learning.",
    courses: 7,
    students: "25k",
    image: "https://example.com/image601.jpg",
    categoryId: 3,
  },
  {
    id: 602,
    title: "Natural Language Processing",
    description: "Understand the basics of NLP and its applications.",
    courses: 6,
    students: "18k",
    image: "https://example.com/image602.jpg",
    categoryId: 3,
  },
  {
    id: 603,
    title: "Reinforcement Learning",
    description: "Learn the fundamentals of reinforcement learning.",
    courses: 5,
    students: "12k",
    image: "https://example.com/image603.jpg",
    categoryId: 3,
  },
  {
    id: 701,
    title: "Cloud Architecture Basics",
    description: "Get started with cloud computing and architecture.",
    courses: 5,
    students: "10k",
    image: "https://example.com/image701.jpg",
    categoryId: 2,
  },
  {
    id: 702,
    title: "Containerization with Docker",
    description: "Learn containerization and Docker for development.",
    courses: 7,
    students: "12k",
    image: "https://example.com/image702.jpg",
    categoryId: 2,
  },
  {
    id: 703,
    title: "Kubernetes for Developers",
    description: "Master Kubernetes for container orchestration.",
    courses: 6,
    students: "15k",
    image: "https://example.com/image703.jpg",
    categoryId: 2,
  },
  {
    id: 801,
    title: "AI Ethics",
    description: "Learn about the ethical implications of AI development.",
    courses: 5,
    students: "7k",
    image: "https://example.com/image801.jpg",
    categoryId: 3,
  },
  {
    id: 802,
    title: "Deploying Machine Learning Models",
    description: "Understand how to deploy ML models in production.",
    courses: 6,
    students: "15k",
    image: "https://example.com/image802.jpg",
    categoryId: 3,
  },
];
